---
title: "65 - Airbnb stays by country"
author: "Felipe Leandro Aguazaco"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: darkly
    highlight: zenburn
    number_sections: true
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = FALSE,
                      cache = TRUE,
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = "center", 
                      #fig.width = 4, 
                      #fig.height = 4,
                      dev = "png")
```

# Problem

---

Suppose you work for Airbnb as an analyst. A team has come to you asking for a ranked list containing total # stays as well as total revenue, split by country. The time frame they're looking for is all stays that began in 2018. You can sort the list in descending order by revenue.  

The table schemas are provided below. Using SQL, write a query to answer this question.  

* Table: property_location_info

| Column Name    | Data Type | Description                                                         |
|----------------|-----------|---------------------------------------------------------------------|
| property_id    | integer   | ID of the property location                                         |
| country        | string    | country code of the property location                               |
| city_name      | string    | name of city (note there can be multiple cities with the same name) |
| subregion_name | string    | provence, state, or subregion name                                  |
| address        | string    | address of property location                                        |
| date_end       | string    | end day of stay, format is "YYYY-mm-dd"                             |
| stay_length    | integer   | number of days for the stay                                         |
| airbnb_revenue | integer   | revenue that Airbnb collected on stay                               |

* Table: stays_info

| Column Name    | Data Type | Description                               |
|----------------|-----------|-------------------------------------------|
| guest_id       | integer   | ID of guest                               |
| property_id    | integer   | ID of the property location               |
| host_id        | integer   | ID of the host managing the property      |
| revenue        | integer   | cost of stay for guest in USD             |
| date_start     | string    | start day of stay, format is "YYYY-mm-dd" |
| date_end       | string    | end day of stay, format is "YYYY-mm-dd"   |
| stay_length    | integer   | number of days for the stay               |
| airbnb_revenue | integer   | revenue that Airbnb collected on stay     |

# Solving Problem 

---

```{sql }
SELECT country, 
       COUNT(guest_id) AS stays, 
       SUM(revenue) AS total_revenue
FROM stays_info
LEFT JOIN property_location_info
  USING(property_id)
WHERE EXTRACT(YEAR FROM date_start) = 2018
GROUP BY country 
ORDER BY total_revenue DESC

```

